### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hadley**
(I didn't rebuild the .md file)

### CODE REVIEW

**Comment by dmi3kno** [comment]
It was definitely meant to be "taking" not "talking". Maybe not the most poetic or even correct verb, but I will stand by it.

**Comment by hadley** [comment]
Hmmm, "requesting" would be more clear than "taking", IMO. Because you don't have a subject, it's not clear exactly what is being taken.

**Comment by dmi3kno** [comment]
Could be. I want to keep my wordplay. 

The polite etiquette over the dinner table would be to *talk slowly* and *listen carefully* (i.e. not ask twice), but here we mean *taking* (downloading) data and memoising (caching). 

Thanks for suggestion and the fact that you felt there's a typo proves that my wordplay worked. I am closing the PR if you don't mind.

**Comment by hadley** [comment]
I don't get the wordplay, but I'll close since it's not a typo.

**Pull request closed without merging**
